/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class nyoba extends javax.swing.JFrame {
    String nm, al, ma, tg;
    int tl;

    /**
     * Creates new form nyoba
     */
    public nyoba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tujuan = new javax.swing.JComboBox<>();
        asal = new javax.swing.JComboBox<>();
        namaka = new javax.swing.JButton();
        bayi = new javax.swing.JComboBox<>();
        dewasa = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel2.setText("E-Mail");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 220, 100, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel3.setText("Nama Pemesan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 100, 20);

        jLabel4.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 100, 20);

        jLabel5.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel5.setText("No Telp");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 100, 20);
        getContentPane().add(mail);
        mail.setBounds(130, 210, 140, 30);
        getContentPane().add(tanggal);
        tanggal.setBounds(500, 90, 140, 30);
        getContentPane().add(alamat);
        alamat.setBounds(130, 130, 140, 30);
        getContentPane().add(telp);
        telp.setBounds(130, 170, 140, 30);

        jLabel6.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel6.setText("Batita");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 270, 60, 20);

        jLabel7.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Keberangkatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 100, 140, 20);

        jLabel8.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel8.setText("Stasiun Asal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 140, 100, 20);

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Kalinga", 1, 12)); // NOI18N
        jLabel9.setText("Stasiun Tujuan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 180, 100, 20);

        jLabel10.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel10.setText("Jumlah Penumpang");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 250, 130, 20);

        jLabel11.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        jLabel11.setText("Dewasa");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 270, 60, 20);

        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malang", "Blitar", "Tulungagung", "Kediri", "Nganjuk", "Madiun" }));
        getContentPane().add(tujuan);
        tujuan.setBounds(500, 170, 140, 30);

        asal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malang", "Blitar", "Tulungagung", "Kediri", "Nganjuk", "Madiun" }));
        asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalActionPerformed(evt);
            }
        });
        getContentPane().add(asal);
        asal.setBounds(500, 130, 140, 30);

        namaka.setText("Jenis KA");
        namaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namakaActionPerformed(evt);
            }
        });
        getContentPane().add(namaka);
        namaka.setBounds(563, 210, 80, 30);

        bayi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4" }));
        getContentPane().add(bayi);
        bayi.setBounds(150, 290, 90, 20);

        dewasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4" }));
        getContentPane().add(dewasa);
        dewasa.setBounds(20, 290, 90, 20);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(130, 90, 140, 30);

        jButton2.setText("PESAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 340, 80, 30);

        jButton3.setText("BATAL");
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 340, 80, 30);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("KERETA API MOKLET");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(228, 11, 336, 46);

        jLabel12.setIcon(new javax.swing.ImageIcon("G:\\ge um22c.gif")); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 60, 680, 360);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 330);

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Copyright 2016 Kelompok 3");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Nanta, Dani, Dini, Made, Sheila");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 330, 700, 150);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(360, 100, 120, 100);

        setBounds(0, 0, 715, 522);
    }// </editor-fold>//GEN-END:initComponents

    private void asalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Nama = nama.getText();
        String Alamat = alamat.getText();
        int No = Integer.parseInt(telp.getText());
        String Email = mail.getText();
        String Tanggal = tanggal.getText();
        String Penumpang1 = dewasa.getSelectedItem().toString();
        String Penumpang2 = bayi.getSelectedItem().toString();
        String Awal = asal.getSelectedItem().toString();
        String Akhir = tujuan.getSelectedItem().toString();
        
        
        
        new nyoba2(Nama, Alamat, No, Email, Tanggal, Penumpang1, Penumpang2, Awal, Akhir).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void namakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namakaActionPerformed
        
    }//GEN-LAST:event_namakaActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nyoba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> asal;
    private javax.swing.JComboBox<String> bayi;
    private javax.swing.JComboBox<String> dewasa;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nama;
    private javax.swing.JButton namaka;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField telp;
    private javax.swing.JComboBox<String> tujuan;
    // End of variables declaration//GEN-END:variables
}
